cache_dir: /Users/dilipp/HDC-LNN2/datasets
categorical_columns:
- protocol_type
- service
- flag
- land
- logged_in
- is_host_login
- is_guest_login
columns:
- duration
- protocol_type
- service
- flag
- src_bytes
- dst_bytes
- land
- wrong_fragment
- urgent
- hot
- num_failed_logins
- logged_in
- num_compromised
- root_shell
- su_attempted
- num_root
- num_file_creations
- num_shells
- num_access_files
- num_outbound_cmds
- is_host_login
- is_guest_login
- count
- srv_count
- serror_rate
- srv_serror_rate
- rerror_rate
- srv_rerror_rate
- same_srv_rate
- diff_srv_rate
- srv_diff_host_rate
- dst_host_count
- dst_host_srv_count
- dst_host_same_srv_rate
- dst_host_diff_srv_rate
- dst_host_same_src_port_rate
- dst_host_srv_diff_host_rate
- dst_host_serror_rate
- dst_host_srv_serror_rate
- dst_host_rerror_rate
- dst_host_srv_rerror_rate
- labels
data:
  cache_dir: data/raw
  dataset_name: unsw_nb15
  split_version: v1
dataset_name: kdd
divergence:
  mode: mahalanobis
  standardize_z_score: false
  threshold_k: 3.0
download_urls:
  test: ''
  train: ''
entity_id_modulo: 254
file_pattern: kdd_train.csv
hdc:
  continuous_features_range:
  - 0.0
  - 1.0
  dimension: 10000
label_column: labels
model:
  batch_size: 256
  epochs: 2
  hidden_dim: 64
  lr: 0.001
numerical_columns:
- duration
- src_bytes
- dst_bytes
- wrong_fragment
- urgent
- hot
- num_failed_logins
- num_compromised
- root_shell
- su_attempted
- num_root
- num_file_creations
- num_shells
- num_access_files
- num_outbound_cmds
- count
- srv_count
- serror_rate
- srv_serror_rate
- rerror_rate
- srv_rerror_rate
- same_srv_rate
- diff_srv_rate
- srv_diff_host_rate
- dst_host_count
- dst_host_srv_count
- dst_host_same_srv_rate
- dst_host_diff_srv_rate
- dst_host_same_src_port_rate
- dst_host_srv_diff_host_rate
- dst_host_serror_rate
- dst_host_srv_serror_rate
- dst_host_rerror_rate
- dst_host_srv_rerror_rate
pipeline:
  frozen_baseline_path: frozen_baseline_kdd.pt
seed: 42
sublabel_column: labels
